# SPDX-License-Identifier: Apache-2.0
{{- if and .Values.auth.oauth2Proxy.enabled .Values.auth.oauth2Proxy.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.oauth2Proxy.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.oauth2Proxy.secretKey }}: {{ .Values.auth.oauth2Proxy.clientSecret | quote }}
{{- end }}
